# Generated by Django 4.1.4 on 2024-01-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_app', '0002_rename_e_name_employee_last_name_employee_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employeesalary',
            old_name='End_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='employeesalary',
            old_name='Salary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='employeesalary',
            old_name='Start_date',
            new_name='start_date',
        ),
    ]
