# Generated by Django 4.1.4 on 2024-01-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_app', '0003_rename_employee_employeesalary_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='floor',
            new_name='Floor',
        ),
    ]
